### PR TITLE
Migrate to Firebase Cloud Messaging

### PR DESCRIPTION
**Pull request by JFreakDK**

### CODE REVIEW

**Comment by AndrewStratigos** [comment]
Was your version of the sdk working after this commit? I am still getting a 401 error on /enroll

**Comment by JFreakDK** [comment]
> Was your version of the sdk working after this commit? I am still getting a 401 error on /enroll

I don't have any problems with calling /enroll after updating.

**Comment by AndrewStratigos** [comment]
OK thanks

It must be the permissions within auth0.

**Comment by lbalmaceda** [comment]
Hey @JFreakDK 👋 If this is a "migration" PR I don't see any changes in the dependencies. The GCM one is [still in place](https://github.com/auth0/Guardian.Android/blob/master/app/build.gradle#L32). I imagine you'd need to replace that with FCM. Also, there's a breaking change in [this line](https://github.com/auth0/Guardian.Android/pull/80/files#diff-fc8692d24d4231c221d2a5d28106b12bR111) which we **can't accept**.

Can you please add more context on the PR description? e.g. why you need this, what error you're receiving, any logs or stacktraces, etc. This repo lacks PR templates but the more information you provide the faster we can action on it. Thank you

**Comment by JFreakDK** [comment]
I migrated the code we were dependent on in our app. 

The change is breaking because the GCM -> FCM migration requires us to switch from `com.google.android.gms.gcm.GcmListenerService` to `com.google.firebase.messaging.FirebaseMessagingService`. The `onMessageReceived` method we overwrite from that class changed signature and now a `android.os.Bundle` is no longer in the parameters of that method.

**Comment by lbalmaceda** [comment]
According to [this blog post](https://firebase.googleblog.com/2018/04/time-to-upgrade-from-gcm-to-fcm.html)


--------

#### What happens to my users who don't update their apps?

As long as users have GCM logic in their apps, they will still receive messages. FCM is backwards compatible with GCM, so even if you don't update your server endpoint now, you can still update your app's logic, and vice versa.

**Comment by silvinamoyano** [comment]
Hi All,
We also are interested in upgrading to FCM.
We understand that if we change the BE endpoint to FCM, push notifications will be stil working.
However, there are some points we need to evaluate in order to analyze possible risks in our App:
- Following this documentation: https://developers.google.com/cloud-messaging/android/android-migrate-fcm:
* "GCM and FCM SDKs cannot co-exist within an application."
So, we can't implement Guardian SDK in our App if It's using FCM to receive other push notifications.
- According documentation: https://developers.google.com/cloud-messaging/faq:
* "I use a product that wraps GCM (such as UrbanAirship). How will GCM deprecation affect me? GCM tokens will continue to work on client devices. However, you should reach out to your provider for more details about what this means for you. "
* "How long do I have to migrate to FCM? We will turn off most GCM services in April 2019, so you should plan to have most of your services migrated by then. Note that client SDKs and GCM tokens will continue to work indefinitely. However, you won't be able to target the latest version of Google Play Services in your Android app unless you migrate to FCM. "
It's not a good idea to have the Google Play Services version limited in our App.
Thanks.

**Comment by lbalmaceda** [comment]
This was resolved in a separate PR, and will be fixed on version 0.4.0

**Pull request closed without merging**
